### ISSUE TITLE
Gens Hex editor corrupted menu labels

### ISSUE THREAD

**Issue by tvoybro** [lab313ru/smd_ida_tools2#1]
![image](https://user-images.githubusercontent.com/40628707/117161570-af3de400-adca-11eb-9ece-4d676a386802.png)

**Comment by lab313ru** [comment]
It looks like now it has been fixed: https://github.com/lab313ru/smd_ida_tools2/commit/b8c67a49306d1fe1a659acac18e5feffffec23e0
