### ISSUE TITLE
Conditional breakpoints crash

### ISSUE THREAD

**Issue by powerpall** [lab313ru/smd_ida_tools2#11]
Conditional breakpoints are a great feature, but they don't work.
I tested the example with A3 register from your documentation (both on IDA 7.7 and IDA9) but it didn't work and the debugger crashed.

![image](https://github.com/user-attachments/assets/b481c1f5-0368-40a9-95ce-bc843841915f)

**Comment by lab313ru** [comment]
Could you provide your conditional bp script?

**Comment by powerpall** [comment]
Oh, turns out that I had a zoo of Python: 2.7, 3.6, 3.9 and 3.12. Everything was ok after uninstalling version 3.12. Now this crash doesn't happen (IDA 7.7), so it looks like the problem is not in your code. My apologies.
