### ISSUE TITLE
Rebuild Gens z80

### ISSUE THREAD

**Issue by anatsvit** [lab313ru/smd_ida_tools2#4]
Сейчас, когда ставишь брейкпоинт, IDA при дебаге z80 показывает не тот IP, и дебаг прыгает не туда (он прыгает на адрес в SP, а должен на адрес в IP), в видео реверсе z80 сделали rebuild, и проблема исчезла, но в релизе она есть

**Comment by lab313ru** [comment]
Привет. Выложу пересобранный к выходным

**Comment by lab313ru** [comment]
Я понимаю, что поздно:), но я думаю должно быть уже пофикшено.
