### ISSUE TITLE
Ida offsets hints

### ISSUE THREAD

**Issue by bonusrd** [lab313ru/smd_ida_tools2#5]
Можно ли исправить подсказки при отладке при доступе к адресным регистрам по индексу?
Например, имеем команду move.l  $20(a5),d0, при этом в а5 некоторый адрес в ram. При наведении курсора на $20(a5) ошибочно отображается некий адрес в роме.

**Comment by lab313ru** [comment]
Можешь сказать название рома и картинку с адресом приложить?

**Comment by bonusrd** [comment]
Ultimate Mortal Kombat 3 (U) [!].gen
![1](https://user-images.githubusercontent.com/66936102/213729709-5cfe83b8-36a3-4e73-9d36-d7a86dc5cac4.png)

**Comment by lab313ru** [comment]
При каких условиях вызывается данный код?

**Comment by bonusrd** [comment]
Выбрать любой режим игры, любого бойца, дождаться начала боя. Также например эта функция вызывается при переходе в блок (зажать B).

**Comment by lab313ru** [comment]
Поправлено в свежем релизе.
