### ISSUE TITLE
Conditional breakpoints

### ISSUE THREAD

**Issue by KingDontCome** [lab313ru/smd_ida_tools2#6]
Breakpoints with conditions do not work (any condition is ignored). Is it possible to fix this problem?

**Comment by lab313ru** [comment]
Hi. I'll check it.

**Comment by DramaDesu** [comment]
@KingDontCome You could check this out:
https://github.com/lab313ru/smd_ida_tools2/compare/main...DramaDesu:smd_ida_tools2:features/gens_helper_window

**Comment by KingDontCome** [comment]
> @KingDontCome You could check this out: [main...DramaDesu:smd_ida_tools2:features/gens_helper_window](https://github.com/lab313ru/smd_ida_tools2/compare/main...DramaDesu:smd_ida_tools2:features/gens_helper_window)

Where can I get the binaries?

**Comment by DramaDesu** [comment]
https://www.emu-land.net/forum/index.php?action=dlattach;topic=72028.0;attach=270311
https://www.emu-land.net/forum/index.php?action=dlattach;topic=72028.0;attach=270312

https://www.emu-land.net/forum/index.php/topic,72028.msg1579112.html#msg1579112

**Comment by DramaDesu** [comment]
A lot of things doesn't work, but you could build up really complex condition
I need to work on syntax 
For now it's possible to compare all data and addr regs, but it's not possible to get value from addr regs, so I will add it, like func to get value from add_regs, may add other regs
There are operations:
==, !=, <=>

**Comment by lab313ru** [comment]
Fixed in: https://github.com/lab313ru/smd_ida_tools2/releases/tag/v2.9
