### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Ushupiuck** [lab313ru/smd_ida_tools2#9]
Why is IDA 7.7 no longer supported by this project?

**Comment by lab313ru** [comment]
Because IDA 8.3 has been leaked and it has no need now to support it.
I know some guys still use IDA 6.6, but I stopped supporting it long time ago.

I'm choosing supported versions by their availability among my users.

**Comment by Ushupiuck** [comment]
Huh, I haven't found it anywhere tbh... other than scam sites

**Comment by lab313ru** [comment]
Rutracker

**Comment by Ushupiuck** [comment]
Gotcha; thanks for the swift reply
